version: '3.9'
services:
  backend:
    build: .
    container_name: backend-chas-advance-dev
    env_file:
      - ../.env
    ports:
      - '3000:3000'
    volumes:
      - .././src/app/src:delegated
      - .././package.json:/app/package.json:ro
      - node_modules:/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: backend-chas-advance-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chas_advance_dev
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  node_modules:
  db-data:
